version: "3.9"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: "timetracker"
      POSTGRES_USER: "timetracker"
      POSTGRES_PASSWORD: "example"
    ports:
      - "5432:5432"
